Set up routing and write controllers
Zel-hub7/blog-app pull request #4
Opened 2023-11-06 18:53 UTC by Zel-hub7

In this project I have created the following.
For each URL I created:

1.A route.
2.An action in the correct controller.
3. A view file.
4. I didnt use the rails generator

2023-11-06 20:04 UTC, Munsa1 requested changes
Hi @Zel-hub7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Created Controllers As Required :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-06 20:04 UTC, Munsa1 commented on app/controllers/posts_controller.rb
> +end
- [ ] KIndly add `Show` actions for the posts controller as well as per requirement.

e.g
`def show; end`

2023-11-06 20:04 UTC, Munsa1 commented on config/routes.rb
>  end
- [ ] It's a requirement to NOT expose unnecessary endpoints in our routes. Since we only have the index and show actions for the Post and User controllers, we should only expose them. In order to do so we need to Use the ONLY keyword to explicitly state which routes are to be used.

e.g
```
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```

2023-11-07 07:27 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @Zel-hub7 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Posts controller has proper action methods ✔
- Only necessary routes are exposed ✔
- Correct use of Git Flow ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 08:34 UTC, merged